### ISSUE TITLE
Dead or outdated links

### ISSUE THREAD

**Issue by thomasveje** [MobilePayDev/MobilePay-Invoice#34]
Hi. In `/docs/index.md` I've found a few links to have problems. 
The ones I've found are under __Best Practice__:

- Read the FAQ's for OpenID Connect <a href="https://developer.mobilepay.dk/faq/integrator">here</a> (*page not found*)
- Integration is based on common standard OpenID Connect. You can find more [here](https://developer.mobilepay.dk/products/openid).  (*Seems like a wrong page is shown*)
- See the video tutorial here [here](https://developer.mobilepay.dk/products/openid/video) (*Same wrong page*)

**Comment by sopbergmann** [comment]
FAQ: https://developer.mobilepay.dk/faq/oidc
OIDC: https://developer.mobilepay.dk/developersupport/openid/
Tutorial: https://developer.mobilepay.dk/developersupport/openid/tutorial
